import { campaignsRepository } from '@/lib/db/repositories/campaigns.repo';
import { subscribersRepository } from '@/lib/db/repositories/subscribers.repo';
import { sendEmail } from '@/lib/email/mailer';
import { fail } from '@/lib/plans';
import { baseUrl } from '@/lib/blog/seo';
import { isSuppressed } from './newsletter.service';
import type { CampaignCreateInput } from './campaign.schema';

// NL-12: 50 messages per CRON-11 batch. NL-18: max 3 attempts then `failed`.
export const CAMPAIGN_BATCH_SIZE = 50;
export const MAX_SEND_ATTEMPTS = 3;
export const AUTO_SEND_DELAY_MINUTES = 15;

function unsubUrl(token: string): string {
  return `${baseUrl()}/newsletter/unsubscribe/${token}`;
}

function clickUrl(campaignId: string, unsubToken: string, target: string): string {
  return `${baseUrl()}/api/newsletter/click?c=${campaignId}&s=${unsubToken}&u=${encodeURIComponent(target)}`;
}

// NL-22: tag links for click-rate measurement (no open-pixel per D-30).
export function tagLinks(html: string, campaignId: string, unsubToken: string): string {
  return html.replace(/href="(https?:[^"]+)"/g, (_, url: string) => {
    if (url.includes('/api/newsletter/click')) return `href="${url}"`;
    return `href="${clickUrl(campaignId, unsubToken, url)}"`;
  });
}

function footerText(locale: string, unsubToken: string): string {
  const url = unsubUrl(unsubToken);
  return locale === 'en'
    ? `\n\nUnsubscribe: ${url}\nNutriClinicEG, Cairo, Egypt`
    : `\n\nإلغاء الاشتراك: ${url}\nNutriClinicEG، القاهرة، مصر`;
}

async function buildAudience(campaignId: string, locale: string, audienceRule: string): Promise<number> {
  // NL-06 suppression gate: confirmed-only, via the shared reader.
  const confirmed = await subscribersRepository.confirmedEmails();
  let queued = 0;
  for (const sub of confirmed) {
    if (audienceRule === 'locale_exact' && sub.locale !== locale) continue;
    // locale_with_fallback: everyone confirmed receives this locale's body (D-28).
    if (await isSuppressed(sub.email)) continue;
    const row = await subscribersRepository.findByEmail(sub.email);
    if (!row) continue;
    if (await campaignsRepository.enqueue(campaignId, row.id)) queued += 1;
  }
  return queued;
}

export const campaignsService = {
  async create(input: CampaignCreateInput, adminId: string): Promise<{ id: string }> {
    const scheduledAt = input.scheduled_at ? new Date(input.scheduled_at) : null;
    const id = await campaignsRepository.insert({
      subject: input.subject.trim(),
      bodyHtml: input.body_html,
      bodyText: input.body_text,
      locale: input.locale,
      createdBy: adminId,
      audienceRule: input.audience_rule ?? 'locale_exact',
      status: scheduledAt ? 'scheduled' : 'draft',
      scheduledAt,
    });
    return { id };
  },

  // NL-26/27/29/30: auto-create on FIRST transition to published only.
  // Returns created campaign ids (one per available locale).
  async autoFromPost(post: {
    id: string; slug: string; locale: string; title: string; excerpt: string | null;
    featured_image: string | null; newsletter_sent_at: Date | string | null;
    send_newsletter: boolean | number | null; published_at: Date | string | null;
    translations?: Array<{ locale: string; title: string; slug: string; excerpt: string | null }>;
  }): Promise<{ ids: string[] }> {
    if (!post.send_newsletter) return { ids: [] };
    if (post.newsletter_sent_at) return { ids: [] }; // NL-27 lock
    const existing = await campaignsRepository.findAutoByPostId(post.id);
    if (existing.length > 0) return { ids: [] };
    const publishedAt = post.published_at ? new Date(post.published_at) : new Date();
    const scheduledAt = new Date(publishedAt.getTime() + AUTO_SEND_DELAY_MINUTES * 60_000);
    const articleUrl = `${baseUrl()}/blog/${post.slug}`;
    const locales = (post.translations && post.translations.length > 0)
      ? [{ locale: post.locale, title: post.title, slug: post.slug, excerpt: post.excerpt },
         ...post.translations.map((t) => ({ locale: t.locale, title: t.title, slug: t.slug, excerpt: t.excerpt }))]
      : [{ locale: post.locale, title: post.title, slug: post.slug, excerpt: post.excerpt }];
    const ids: string[] = [];
    for (const loc of locales) {
      const en = loc.locale === 'en';
      const url = `${baseUrl()}/blog/${loc.slug}`;
      const html = `${post.featured_image ? `<img src="${post.featured_image}" alt="" />` : ''}<p>${loc.excerpt ?? ''}</p><p><a href="${url}">${en ? 'Read the full article' : 'اقرأ المقال كاملًا'}</a></p>`;
      const text = `${loc.excerpt ?? ''}\n${en ? 'Read the full article' : 'اقرأ المقال كاملًا'}: ${url}`;
      void articleUrl;
      const id = await campaignsRepository.insert({
        subject: loc.title,
        bodyHtml: html,
        bodyText: text,
        locale: loc.locale,
        postId: post.id,
        autoGenerated: true,
        // NL-30: single-locale post → fallback audience; translated → exact each.
        audienceRule: locales.length > 1 ? 'locale_exact' : 'locale_with_fallback',
        status: 'scheduled',
        scheduledAt,
      });
      ids.push(id);
    }
    return { ids };
  },

  // NL-28: cancel scheduled auto-campaigns when the post is unpublished/archived.
  async cancelForPost(postId: string, reason: string): Promise<{ cancelled: number }> {
    const autos = await campaignsRepository.findAutoByPostId(postId);
    let cancelled = 0;
    for (const c of autos) {
      if (c.status === 'scheduled' || c.status === 'draft') {
        await campaignsRepository.update(c.id, { status: 'failed' });
        void reason;
        cancelled += 1;
      }
    }
    return { cancelled };
  },

  async update(id: string, patch: { subject?: string; bodyHtml?: string; bodyText?: string; scheduledAt?: Date | null }): Promise<void> {
    const existing = await campaignsRepository.findById(id);
    if (!existing) throw fail('NOT_FOUND', 'Campaign not found');
    if (existing.status !== 'draft' && existing.status !== 'scheduled') {
      throw fail('CAMPAIGN_LOCKED', 'Only draft/scheduled campaigns can be edited');
    }
    await campaignsRepository.update(id, patch);
  },

  async cancel(id: string): Promise<void> {
    const existing = await campaignsRepository.findById(id);
    if (!existing) throw fail('NOT_FOUND', 'Campaign not found');
    if (existing.status !== 'draft' && existing.status !== 'scheduled') {
      throw fail('CAMPAIGN_LOCKED', 'Only draft/scheduled campaigns can be cancelled');
    }
    await campaignsRepository.update(id, { status: 'failed' });
  },

  async launch(id: string): Promise<{ queued: number }> {
    const c = await campaignsRepository.findById(id);
    if (!c) throw fail('NOT_FOUND', 'Campaign not found');
    if (c.status !== 'draft' && c.status !== 'scheduled') {
      throw fail('CAMPAIGN_LOCKED', 'Campaign already launched');
    }
    const queued = await buildAudience(id, c.locale, c.audience_rule);
    await campaignsRepository.update(id, { status: 'sending' });
    return { queued };
  },

  // NL-15: preview + test send to an admin address (never touches the queue).
  async sendTest(id: string, email: string): Promise<void> {
    const c = await campaignsRepository.findById(id);
    if (!c) throw fail('NOT_FOUND', 'Campaign not found');
    const subject = `[Preview] ${c.subject}`;
    await sendEmail({
      to: email, subject,
      text: `${c.body_text}\n\n(Preview — unsubscribe link omitted)`,
      html: `${c.body_html}<hr><p>Preview — unsubscribe link omitted.</p>`,
    });
  },

  // CRON-11 body: send up to 50 queued rows for due campaigns (NL-12).
  async processDue(now = new Date()): Promise<{ campaigns: number; sent: number; failed: number }> {
    const due = await campaignsRepository.dueCampaigns(now);
    let campaigns = 0;
    let sent = 0;
    let failed = 0;
    for (const c of due) {
      if (c.status === 'scheduled') {
        await buildAudience(c.id, c.locale, c.audience_rule);
        await campaignsRepository.update(c.id, { status: 'sending' });
      }
      const batch = await campaignsRepository.nextBatch(c.id, CAMPAIGN_BATCH_SIZE);
      // NL-18: retry previously failed rows (attempts < 3) within the same budget.
      const retries = await campaignsRepository.failedRetryable(c.id, MAX_SEND_ATTEMPTS);
      const work = [...batch, ...retries].slice(0, CAMPAIGN_BATCH_SIZE);
      let cSent = 0;
      let cFailed = 0;
      for (const send of work) {
        try {
          const subs = await subscribersRepository.confirmedEmails();
          void subs;
          // Suppression re-check at send time (NL-06): skip unconfirmed.
          const all = await subscribersRepository.list({ page: 1, limit: 500 });
          const target = all.rows.find((r) => r.id === send.subscriber_id);
          if (!target || target.status !== 'confirmed') {
            await campaignsRepository.markSend(send.id, 'skipped', 'suppressed');
            continue;
          }
          const html = `${tagLinks(c.body_html, c.id, target.unsub_token)}<hr><p><a href="${unsubUrl(target.unsub_token)}">${c.locale === 'en' ? 'Unsubscribe' : 'إلغاء الاشتراك'}</a> · NutriClinicEG, Cairo, Egypt</p>`;
          await sendEmail({
            to: target.email,
            subject: c.subject,
            text: `${c.body_text}${footerText(c.locale, target.unsub_token)}`,
            html,
          });
          await campaignsRepository.markSend(send.id, 'sent');
          cSent += 1;
        } catch (err) {
          await campaignsRepository.markSend(send.id, 'failed', (err as Error).message.slice(0, 500));
          cFailed += 1;
        }
      }
      await campaignsRepository.bumpCounters(c.id, cSent, cFailed);
      const report = await campaignsRepository.report(c.id);
      if (report.queued === 0) await campaignsRepository.markSent(c.id);
      sent += cSent;
      failed += cFailed;
      campaigns += 1;
    }
    return { campaigns, sent, failed };
  },

  async report(id: string) {
    const c = await campaignsRepository.findById(id);
    if (!c) throw fail('NOT_FOUND', 'Campaign not found');
    const sends = await campaignsRepository.report(id);
    return { campaign: c, sends };
  },
};
