import { executeQuery } from '@/lib/db/pool';
import { randomUUID } from 'crypto';

export interface CampaignRow {
  id: string;
  post_id: string | null;
  created_by: string | null;
  subject: string;
  body_html: string;
  body_text: string;
  locale: string;
  auto_generated: boolean;
  audience_rule: 'locale_exact' | 'locale_with_fallback';
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
  scheduled_at: Date | null;
  total_count: number;
  sent_count: number;
  failed_count: number;
  click_count: number;
  sent_at: Date | null;
  created_at: Date;
}

export interface SendRow {
  id: string;
  campaign_id: string;
  subscriber_id: string;
  status: 'queued' | 'sent' | 'failed' | 'skipped';
  attempts: number;
  error_message: string | null;
  sent_at: Date | null;
}

export const campaignsRepository = {
  async insert(data: {
    subject: string; bodyHtml: string; bodyText: string; locale: string;
    postId?: string | null; createdBy?: string | null; autoGenerated?: boolean;
    audienceRule?: 'locale_exact' | 'locale_with_fallback';
    status?: 'draft' | 'scheduled'; scheduledAt?: Date | null;
  }): Promise<string> {
    const id = randomUUID();
    await executeQuery(
      `INSERT INTO NewsletterCampaign (id, post_id, created_by, subject, body_html, body_text, locale, auto_generated, audience_rule, status, scheduled_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [id, data.postId ?? null, data.createdBy ?? null, data.subject, data.bodyHtml, data.bodyText,
        data.locale, data.autoGenerated ? 1 : 0, data.audienceRule ?? 'locale_exact',
        data.status ?? 'draft', data.scheduledAt ?? null]
    );
    return id;
  },

  async findById(id: string): Promise<CampaignRow | null> {
    const rows = await executeQuery<CampaignRow[]>('SELECT * FROM NewsletterCampaign WHERE id = ?', [id]);
    return rows.length > 0 ? rows[0] : null;
  },

  async findAutoByPostId(postId: string): Promise<CampaignRow[]> {
    return executeQuery<CampaignRow[]>(
      'SELECT * FROM NewsletterCampaign WHERE post_id = ? AND auto_generated = 1', [postId]
    );
  },

  async list(filters: { status?: string; page?: number; limit?: number }): Promise<{ rows: CampaignRow[]; total: number }> {
    const page = filters.page ?? 1;
    const limit = Math.min(filters.limit ?? 20, 100);
    const offset = (page - 1) * limit;
    const params: Array<string | number> = [];
    const clause = filters.status ? 'WHERE status = ?' : '';
    if (filters.status) params.push(filters.status);
    const rows = await executeQuery<CampaignRow[]>(
      // eslint-disable-next-line no-restricted-syntax -- clause is fixed; values use ? placeholders (D-01)
      `SELECT * FROM NewsletterCampaign ${clause} ORDER BY created_at DESC LIMIT ? OFFSET ?`,
      [...params, limit, offset]
    );
    const totalRows = await executeQuery<Array<{ count: number }>>(
      // eslint-disable-next-line no-restricted-syntax -- clause is fixed; values use ? placeholders (D-01)
      `SELECT COUNT(*) as count FROM NewsletterCampaign ${clause}`,
      params
    );
    return { rows, total: Number(totalRows[0].count) };
  },

  async update(id: string, patch: { subject?: string; bodyHtml?: string; bodyText?: string; scheduledAt?: Date | null; status?: CampaignRow['status'] }): Promise<void> {
    const sets: string[] = [];
    const params: Array<string | Date | number | null> = [];
    if (patch.subject !== undefined) { sets.push('subject = ?'); params.push(patch.subject); }
    if (patch.bodyHtml !== undefined) { sets.push('body_html = ?'); params.push(patch.bodyHtml); }
    if (patch.bodyText !== undefined) { sets.push('body_text = ?'); params.push(patch.bodyText); }
    if (patch.scheduledAt !== undefined) { sets.push('scheduled_at = ?'); params.push(patch.scheduledAt); }
    if (patch.status !== undefined) { sets.push('status = ?'); params.push(patch.status); }
    if (sets.length === 0) return;
    await executeQuery(
      // eslint-disable-next-line no-restricted-syntax -- SET fragments are fixed; values use ? placeholders (D-01)
      `UPDATE NewsletterCampaign SET ${sets.join(', ')} WHERE id = ?`,
      [...params, id]
    );
  },

  async bumpCounters(id: string, sent: number, failed: number): Promise<void> {
    await executeQuery(
      'UPDATE NewsletterCampaign SET sent_count = sent_count + ?, failed_count = failed_count + ? WHERE id = ?',
      [sent, failed, id]
    );
  },

  async incrementClicks(id: string): Promise<void> {
    await executeQuery('UPDATE NewsletterCampaign SET click_count = click_count + 1 WHERE id = ?', [id]);
  },

  async markSent(id: string): Promise<void> {
    await executeQuery(
      "UPDATE NewsletterCampaign SET status = 'sent', sent_at = ? WHERE id = ?",
      [new Date(), id]
    );
  },

  // NL-16: one row per (campaign, subscriber); duplicates are ignored.
  async enqueue(campaignId: string, subscriberId: string): Promise<boolean> {
    try {
      await executeQuery(
        "INSERT INTO NewsletterSend (id, campaign_id, subscriber_id, status) VALUES (?, ?, ?, 'queued')",
        [randomUUID(), campaignId, subscriberId]
      );
      return true;
    } catch {
      return false; // uq_campaign_subscriber hit → already queued/sent
    }
  },

  async nextBatch(campaignId: string, limit: number): Promise<SendRow[]> {
    return executeQuery<SendRow[]>(
      'SELECT * FROM NewsletterSend WHERE campaign_id = ? AND status = ? ORDER BY id ASC LIMIT ?',
      [campaignId, 'queued', limit]
    );
  },

  async failedRetryable(campaignId: string, maxAttempts: number): Promise<SendRow[]> {
    return executeQuery<SendRow[]>(
      'SELECT * FROM NewsletterSend WHERE campaign_id = ? AND status = ? AND attempts < ? ORDER BY id ASC LIMIT 50',
      [campaignId, 'failed', maxAttempts]
    );
  },

  async markSend(id: string, status: 'sent' | 'failed' | 'skipped', error: string | null = null): Promise<void> {
    await executeQuery(
      'UPDATE NewsletterSend SET status = ?, attempts = attempts + 1, error_message = ?, sent_at = ? WHERE id = ?',
      [status, error, status === 'sent' ? new Date() : null, id]
    );
  },

  async report(campaignId: string): Promise<{ sent: number; failed: number; queued: number; skipped: number }> {
    const rows = await executeQuery<Array<{ status: string; count: number }>>(
      'SELECT status, COUNT(*) as count FROM NewsletterSend WHERE campaign_id = ? GROUP BY status', [campaignId]
    );
    const out = { sent: 0, failed: 0, queued: 0, skipped: 0 };
    for (const r of rows) {
      if (r.status in out) out[r.status as keyof typeof out] = Number(r.count);
    }
    return out;
  },

  async dueCampaigns(now = new Date()): Promise<CampaignRow[]> {
    return executeQuery<CampaignRow[]>(
      "SELECT * FROM NewsletterCampaign WHERE status = 'scheduled' AND scheduled_at IS NOT NULL AND scheduled_at <= ? ORDER BY scheduled_at ASC LIMIT 10",
      [now]
    );
  },
};
